code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension esbenp.prettier-vscode
code --install-extension fabianlauer.vs-code-xml-format
code --install-extension golang.go
code --install-extension grapecity.gc-excelviewer
code --install-extension hussamadil.ayat
code --install-extension icrawl.discord-vscode
code --install-extension jakeboone02.cypher-query-language
code --install-extension james-yu.latex-workshop
code --install-extension jebbs.plantuml
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.powershell
code --install-extension redhat.java
code --install-extension ritwickdey.liveserver
code --install-extension svelte.svelte-vscode
code --install-extension tal7aouy.icons
code --install-extension tauri-apps.tauri-vscode
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wwnao.bat-formatter
code --install-extension yy0931.vscode-sqlite3-editor
